### ISSUE TITLE
Use pretrained model to test on my dataset

### ISSUE THREAD

**Issue by ting-chih** [yunzhusong/NAACL2022-REFLECT#3]
Hi, 
thanks for your release. I want to inference your pre-trained model on my dataset. Could you tell me how to use?

thanks,

**Comment by ting-chih** [comment]
How can I reproduce my dataset like your format?

**Comment by yunzhusong** [comment]
Hi, thank you for being interested in our work. We have updated the code to reorganize the scripts and for better understanding, please reload the code. Besides, It might be helpful to check the scripts if you would like to construct your own dataset for our model.

To run a new dataset, please add the data information of _summarization_name_mapping, summarization_length_mapping, summarization_own_file_mapping_ in **src/data/build_datasets.py** first to facilitate the _data_args.dataset_name_.

To build the dataset that fits our format, I would recommend you construct the raw dataset following the format of Multi-News (note that the Multi-News has been a little revised recently, we have modified the code accordingly). Then, follow the **scripts/construct_dataset_end2end.sh** to build the dataset end-to-end from step 2. 
P.S. For the _step 3. build summary reference_, you might want to train a summarizer on your dataset in advance using the script in scripts/run.sh, and assign the **model_name_or_path** in **scripts/construct_dataset_end2end.sh** accordingly. Otherwise, you could follow the default setting that adopts a model pretrained on Multi-News to obtain the summary reference.

Feel free to let me know if there is any other issue, thanks!
